name: Build, Sign & Release
on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!i18n/src/commonMain/moko-resources/**/strings.xml'
      - '!i18n/src/commonMain/moko-resources/**/plurals.xml'
      - 'i18n/src/commonMain/moko-resources/base/strings.xml'
      - 'i18n/src/commonMain/moko-resources/base/plurals.xml'
  push:
    branches: [main]
    tags: ['v*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build & Test App
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release APK
        run: ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater

      - name: Store APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            app/build/outputs/apk/release/*-release-unsigned.apk
            app/build/outputs/mapping/release

  sign-and-release:
    name: Sign and Release
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          name: app-apks
          path: artifacts/

      - name: Sign APKs
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: artifacts
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*-release-signed.apk
            artifacts/release/mapping.txt
          generate_release_notes: true
